name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  GCC-build:
    runs-on: ${{ matrix.image }}

    strategy:
      matrix:
        image: [ 'ubuntu-20.04' ]
        GCC: [ '9', '11' ]
        BUILD_TYPE: [ 'Release' ]
        include:
          - image: 'ubuntu-latest'
            GCC: '12'
            BUILD_TYPE: 'Debug'

    steps:
    - uses: actions/checkout@v4
    - uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "~3.25.0"

    - name: Install GCC
      run: sudo apt update && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install g++-${{ matrix.GCC }} gfortran-${{ matrix.GCC }} gcc-${{ matrix.GCC }}

    - name: Install cffi
      run: pip install --user cffi

    - name: Configure CMake
      run: cmake -G"Ninja"  -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_C_COMPILER=gcc-${{ matrix.GCC }} -DCMAKE_CXX_COMPILER=g++-${{ matrix.GCC }} -DCMAKE_Fortran_COMPILER=gfortran-${{ matrix.GCC }} -DENABLE_OPENMP=ON -DUSE_LIBINT=OFF -DLINALG_LIB_INT64=OFF  -DCMAKE_INSTALL_PREFIX=.

    - name: Build
      run: ninja -C build install

    - name: Instal pyoqp
      working-directory: ${{github.workspace}}/pyoqp
      run: pip install --user .
